### ISSUE TITLE
Is Squarespace a bad choice for SEO?

### ISSUE THREAD

**Issue by mbalkon** [chuckreynolds/ama#10]
Hey Mr. Chuck!

I have a client interested in using Squarespace for a starter site. They're not very tech savvy, have a very small budget, and are simply looking for a simple brochure site, so I thought Squarespace could be a good place for them to get started. However, their SEO person is telling them they need to use WP for SEO reasons. Isn't text on a Squarespace page just as searchable by Google as text on a WP page?

**Got any insight for me to pass on to my client?**

Their SEO person sent them the following screenshot from the Squarespace site:

![img_0313](https://cloud.githubusercontent.com/assets/4261229/15090966/f8258c1c-13ed-11e6-97a5-5ceaa54b29be.PNG)

**Comment by chuckreynolds** [comment]
I wouldn't say it's a BAD idea but anything that's hosted like that probably has some down sides when it comes to customizability. I'm not very knowledgeable on the squarespace environment and how much they have in there for you in regards to meta information and schema etc... but couple things here.

"Small budget" & "simple brochure site" & "not tech savvy" but they have an "SEO person"?... those don't typically lend themselves to a highly technical need for actual deep search optimization; nor does it seem to be content rich environment to begin with. What Squarespace provides out of the box seems to be exactly enough of what you'd need. IE page settings allow meta titles and meta descriptions to be customized per page. seems to allow robots.txt editing and easier than DNS verification of Google Webmaster Tools etc. I mean if those are all setup properly; that's already better than a lot of sites have it now. 

Theme selection in SS will take priority in regard to how well the content of the site is represented to search bots. If you pick some crazy one-page ajax-y/scroll-y type site then that can screw with the content architecture; but if a well-coded theme that loads quickly is your choice then this shouldn't be too much of an issue. 

It seems they've mentioned "twitter cards" and "OGP"... those are good to have but not necessarily anything really to do with SEO; they did seem to say "marketing reasons" but that's a different thing entirely. Regardless; as far as I can tell SS allows you to edit the theme from their interface and adding the meta code that TwitterCards gives you and adding Open Graph meta tags to the theme's header or main include file with the `<head>` stuff in it... will do just fine. And if they want to add per-page variables like that page title/description for the twitter share / facebook share... i'm fairly certain SS has template tags available for themes that will do that for you. 

Anyways... the whole SS isn't as good as WP thing... for the ballpark you're batting in... you'll do just fine on Square Space. And when there are "not tech savvy" people involved in ownership and management... it's good to have them on a hosted environment like SS with good support and plenty of developers around to help edit themes. In this regard there's nothing SS can't do for you and your client at this time. Use SS. :)

Thanks for asking!!!  Cheers

**Comment by chuckreynolds** [comment]
Couple links to help with what I've discussed:
- http://developers.squarespace.com/templating-basics/
- https://support.squarespace.com/hc/en-us/articles/206543937
- https://dev.twitter.com/cards/types/summary
- https://developers.facebook.com/docs/sharing/webmasters

**Comment by mbalkon** [comment]
Thank you so much, Chuck!!

---

Melissa Balkon
*Founder + Design Strategist, Strong Design*

480-327-8804
@melissabalkon
www.strongdesign.co

Need to chat? Schedule a call here: calendly.com/mbalkon

* NOTE:* I will be out of the office from May 15–June 1 with no email
access.
