### ISSUE TITLE
Best route to Building on intermediate SEO  knowledge?

### ISSUE THREAD

**Issue by gravymatt** [chuckreynolds/ama#11]
DO you have any suggested books or SEO 101 and SEO 102?

Do you have Best route (blogs, books, onoline courses) to Building on intermediate SEO  knowledge?

Thanks,
Gravy

**Comment by chuckreynolds** [comment]
Hmm... I'd say start with [Google's Starter Guide](http://static.googleusercontent.com/external_content/untrusted_dlcp/www.google.com/en/us/webmasters/docs/search-engine-optimization-starter-guide.pdf). That probably has the most beginner level information and directly from the source who defines most of what happens in search optimization these days. 

Another thing to read through is probably [Moz's Beginner's Guide](https://moz.com/beginners-guide-to-seo). 
Maybe look at [Search engine land's guide](http://searchengineland.com/guide/what-is-seo) with a bunch of links too.

From there, if you don't already, learn about building clean HTML and CSS sites and how front-end code and content organization and structure help when building new sites or optimizing current ones. 

Then you'll need to start looking at your search rankings in Google, and competitors, and monitoring the changes you make on the site and how those effect what happens in those results. And from there you'll just fall into the rabbit hole..... and it goes as deep as you'd like to venture. 

Hope that helps. Good luck. Cheers!
